server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://localhost:5422/jwt_auth
    username: keycloack
    password: keycloack
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/crm
jackson:
  serialization:
    indent-output: true
  deserialization:
    fail-on-unknown-properties: false
  default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

 


# JWT configs (usaremos mais tarde)
jwt:
  secret: minhachavesecreta1234567890
  expiration: 600000              # 10 minutos
  refresh-expiration: 604800000  # 7 dias (em ms)
keycloak:
  issuer-uri: http://localhost:8080/realms/crm
  client-id: crm-api
